name: Xcode Build for Example App

on:
  workflow_dispatch:
  push:
    branches: [ tretnfckit-main ]
  pull_request:
    branches: [ tretnfckit-main ]

env:
  SCHEME_NAME: TRETNFCKitExample
  IOS_SIMULATOR_NAME: iPhone 14 Pro
  XCODE_SELECT_PATH: '/Applications/Xcode_14.1.app/Contents/Developer'

jobs:
  show_software_information:
    name: Show software information
    strategy:
      fail-fast: false
      matrix:
        os: [macos-12]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Show Xcode list
      run: ls -n /Applications | grep 'Xcode'
    - name: Show the default version of Xcode
      run: xcodebuild -version
    - name: Set Xcode version
      run: sudo xcode-select -s '${{ env.XCODE_SELECT_PATH }}'
    - name: Show lists the targets and configurations in a project, or the schemes in a workspace
      run: xcodebuild -list
      working-directory: ./Examples
    - name: Show a list of destinations
      run: xcodebuild -scheme ${{ env.SCHEME_NAME }} -showdestinations
      working-directory: ./Examples
    
  xcodebuild:
    name: Xcode Build
    strategy:
      fail-fast: false
      matrix:
        os: [macos-12]
        platform: ['iOS']
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Set Xcode version
      run: sudo xcode-select -s '${{ env.XCODE_SELECT_PATH }}'
    - name: Build the scheme
      run: |
        case ${{ matrix.platform }} in
          'iOS' ) xcodebuild -scheme ${{ env.SCHEME_NAME }} -destination 'name=${{ env.IOS_SIMULATOR_NAME }}' | tee xcodebuild-${{ matrix.platform }}.log && exit ${PIPESTATUS[0]} ;;
        esac
      working-directory: ./Examples
    - name: Upload Xcode Build log
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: xcodebuild log (${{ matrix.platform }})
        path: |
            Examples/xcodebuild-${{ matrix.platform }}.log
    - name: Upload Xcode DerivedData
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: Xcode DerivedData (${{ matrix.platform }})
        path: |
            /Users/runner/Library/Developer/Xcode/DerivedData
